### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by basilevh** [gzdshn/hoot-toolkit#3]
Hi,

I see that the script is trying to access http://ilab.usc.edu/hoot/v1_0/HD/metadata.json, however it does not work:

```
    assert response.status_code == HTTPStatus.OK, f'Service returned error {response.status_code}'
AssertionError: Service returned error 403
```

I am interested in using your data, so would you please mind looking into this?  Perhaps I am doing something wrong, or there might be an issue with the public permissions of the data hosting service?

Thank you in advance!

**Comment by halee88** [comment]
Hi @basilevh

Thank you for reporting this. There was an outage at the host which has been fixed recently! Try downloading again and let me know if it works

**Comment by Vishwa2684** [comment]
@halee88 

https://github.com/gzdshn/hoot-toolkit/issues/5
